spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${keycloak.client-id}
            client-secret: ${keycloak.client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
            user-name-attribute: preferred_username

  # Thymeleaf ??????????
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8081

keycloak:
  server-url: http://localhost:8080
  token-url: ${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/token
  realm: master
  client-id: admin-cli
  client-secret: bTCuwQqrSeV9sWTFJC9OzL0OSkyYhPIz
  username: admin
  password: fairy-vip
